import React from 'react'
import { motion } from 'framer-motion'
import { CheckCircle2, Play, GitBranch, Zap, Sparkles } from 'lucide-react'
import AIChatPanel from '@/components/AIChatPanel'

export default function Workflow() {
  const steps = [
    {
      id: 1,
      title: 'Analyze & Suggest',
      desc: 'The integrated LLM processes code blocks and explains complex logic in simple markdown terms.',
      icon: <Sparkles className="text-purple-400" size={16} />
    },
    {
      id: 2,
      title: 'Optimized Refactoring',
      desc: 'Get immediate performance feedback, cache suggestions, and computational complexity benchmarks.',
      icon: <Zap className="text-cyan-400" size={16} />
    },
    {
      id: 3,
      title: 'Git Versioning',
      desc: 'Stage, review diff cards, and commit changes with descriptive titles generated by local AI.',
      icon: <GitBranch className="text-emerald-400" size={16} />
    }
  ]

  return (
    <section className="py-24 px-6 bg-[#040508] relative overflow-hidden">
      {/* Visual background divider line */}
      <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-white/[0.04] to-transparent" />

      <div className="max-w-7xl w-full mx-auto grid grid-cols-1 lg:grid-cols-12 gap-16 items-center">
        {/* Left: Workflow Explanations */}
        <div className="lg:col-span-5 flex flex-col gap-8 text-left">
          <div>
            <h2 className="text-xs font-bold uppercase tracking-widest text-[#a855f7] mb-2">Simulate Integration</h2>
            <h3 className="text-3xl sm:text-4xl font-extrabold text-white tracking-tight">
              An AI Companion That Lives in Your Codebase
            </h3>
            <p className="mt-4 text-sm text-slate-400 leading-relaxed">
              Ditch context switching. Ask queries, debug syntax warnings, and apply code patches in a high-fidelity interface.
            </p>
          </div>

          <div className="flex flex-col gap-6">
            {steps.map((step) => (
              <motion.div
                key={step.id}
                whileHover={{ x: 4 }}
                className="flex items-start gap-4 p-4 rounded-xl border border-white/[0.03] bg-white/[0.01] hover:bg-white/[0.03] transition-all"
              >
                <div className="w-8 h-8 rounded-lg flex items-center justify-center bg-white/[0.02] border border-white/[0.06] shrink-0 mt-0.5">
                  {step.icon}
                </div>
                <div>
                  <h4 className="text-[13px] font-bold text-slate-200">{step.title}</h4>
                  <p className="text-[11px] text-slate-400 mt-1 leading-relaxed">{step.desc}</p>
                </div>
              </motion.div>
            ))}
          </div>
        </div>

        {/* Right: Live Interactive AIChatPanel Demo */}
        <div className="lg:col-span-7 flex justify-center">
          <div className="w-full max-w-[440px] h-[520px] rounded-2xl border border-[#a855f7]/15 shadow-[0_0_40px_rgba(139,92,246,0.06)] relative overflow-hidden bg-[#07080c]/50">
            {/* Edge decorative border accents */}
            <div className="absolute top-0 left-0 right-0 h-px bg-gradient-to-r from-transparent via-[#a855f7]/40 to-transparent" />
            
            <div className="absolute inset-0 p-1.5 flex flex-col h-full">
              <div className="flex items-center justify-between px-3 py-1.5 bg-[#090a10]/95 border border-white/[0.04] rounded-xl mb-1.5 select-none">
                <div className="flex items-center gap-1.5">
                  <div className="w-2 h-2 rounded-full bg-emerald-400 animate-pulse" />
                  <span className="text-[10px] font-bold text-slate-300 font-sans tracking-wide">LIVE CO-PILOT VIEW</span>
                </div>
                <span className="text-[9px] text-slate-600 font-mono">Press Enter to chat</span>
              </div>
              
              <div className="flex-1 min-h-0">
                <AIChatPanel />
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
